### ISSUE TITLE
getUtilization returns number higher than 1

### ISSUE THREAD

**Issue by martinklepsch** [ztellman/dirigiste#14]
I'm just experimenting with dirigiste at this point and am a bit confused by the fact that `getUtilization` returns 1.5 for me in some cases. With the below snippet if I run `(.acquire p :foo)` three times the Utilization log message will print 1.5. (Acquiring three `:foo` acquires without releasing causes the `.acquire` call to block since the pool will not allocate any more objects.)

Is that expected or to be considered a bug? 

```clojure
(ns my.pool
  (:require [clojure.tools.logging :as log])
  (:import [java.util.concurrent TimeUnit]
           [io.aleph.dirigiste Pools Pool IPool$Generator IPool$Controller])) 

(defn generator [disposed]
  (let [cnt (atom 0)]
    (reify IPool$Generator
      (generate [_ k]
        (log/info "Generating new object for key" k)
        (Thread/sleep (* @cnt 1000))
        (swap! cnt inc))
      (destroy [_ k v]
        (log/info "Disposing" k v)
        (swap! disposed conj [k v])))))

(def stats (atom nil))

(defn controller [min-objects max-total-objects]
  (reify IPool$Controller
    (shouldIncrement [_ key objects-for-key total-objects]
      (and (< total-objects max-total-objects)
           (< objects-for-key min-objects)))
    (adjustment [_ key->stats]
      (when (:foo key->stats)
        (log/info "Utilization" (.getUtilization (:foo key->stats) 0.9))
        (log/info "Num Workers" (.getNumWorkers (:foo key->stats)))
        (log/info "Mean Queue Length" (.getMeanQueueLength (:foo key->stats))))
      (reset! stats key->stats)
      {:foo (int (max min-objects ))
       :bar (int (max min-objects ))})))

(def p
  (Pool. (generator (atom nil)) (controller 2 10) 1e5 25 1e4 TimeUnit/MILLISECONDS))
```

**Comment by martinklepsch** [comment]
Another thing that confuses me in this regard: When aquiring one `:foo` should the utilization increase?

I'm trying to write a controller that ensures 
- there's always a pooled object ready (i.e. I never want to wait when acquiring an object)
- and that an object is never destroyed just because it's not needed right now.

But so far I'm struggling 😄 — if any one has advice I'll gladly take it 🙂

**Comment by ztellman** [comment]
The 1.5 utilization is because there are only two objects in the pool, and three desired objects (because your generator is sleeping).  The key line of code here is https://github.com/ztellman/dirigiste/blob/master/src/io/aleph/dirigiste/Pool.java#L310.

As for why it's not increasing, I'm not sure.  You're getting the p90 utilization, maybe try the p100 and see if it's just a question of how many samples there are?

**Comment by martinklepsch** [comment]
It makes sense that utilization is at 1.5 in the way you described. It's not what the documentation describes however.

After a bit more testing I decided to go with Apache commons-pool which supports my (perhaps unusual) use-case  better so feel free to close this issue if you don't think there is something that needs changing.

**Comment by alexander-yakushev** [comment]
@martinklepsch In case this might be still relevant for you, #23 made utilization calculation more predictable.

**Comment by martinklepsch** [comment]
No longer relevant at this point but thanks for the heads up. I'll close this issue.
