### ISSUE TITLE
Divide by zero in mean calculation in Stats.java

### ISSUE THREAD

**Issue by brendanyounger** [ztellman/dirigiste#15]
A divide by zero exception can occur in the mean calculation here https://github.com/ztellman/dirigiste/blob/master/src/io/aleph/dirigiste/Stats.java#L227 when vals is not null but does have length 0.

**Comment by brendanyounger** [comment]
I should have been more explicit, but the same issue is still present in the double version of `mean` as well.

**Comment by ztellman** [comment]
Of course, sorry, running on autopilot.
