### ISSUE TITLE
Extracting an interface from concrete Pool

### ISSUE THREAD

**Issue by bts** [ztellman/dirigiste#2]
Hi Zach,

I was wondering if you'd be opposed to the idea of extracting an interface from the single concrete `Pool` implementation? I've been considering wrapping the current `Pool` with some extra logic in `acquire`.

FWIW I'm considering putting a rate limit in `acquire` (per key) that I could plug into aleph. While I could theoretically try to limit requests/second indirectly by controlling connection allocation via a custom `Pool.Controller`, (1) I'd prefer to have more immediate control at the point of acquisition (vs delayed adjustments), and (2) it might even be possible that in certain circumstances with short enough requests that I could exceed a rate limit using only a single connection, rendering the controller approach ineffective.

Would my wrapping and delaying calls to the underlying `acquire` defeat the semantics of dirigiste's pooling in any way?

If you think extracting an interface would be alright, I'd be more than happy to submit a patch. Thanks for all of your libraries -- I've been finding them really useful.

Thanks,
Brian

**Comment by ztellman** [comment]
No objections to having it be an interface, it's an obvious parallel to the ExecutorService interface used elsewhere.

**Comment by bts** [comment]
If we use `Pool` for the interface name, any preference for what to call the concrete impl?

**Comment by ztellman** [comment]
Can we just call it `IPool`?  I'm not feeling too imaginative.

**Comment by bts** [comment]
Sounds good. I'll submit a PR sometime soon.
