### ISSUE TITLE
Takes aren't dequeued when `generate` throws

### ISSUE THREAD

**Issue by dm3** [ztellman/dirigiste#7]
Please see the following test: https://github.com/dm3/dirigiste/commit/387548bef4f59559c0c0d1e46cc4c3e1b0465e12

The issue is in the `Pool$Queue` which adds a pending take and never removes if the generator throws. I stumbled into the issue when trying to create an Aleph TCP client with a fixed pool of connections and no room for waiting (`:max-queue-size 1`). 

I think this is a real issue with Dirigiste, but at the same time please point me in the right direction if my design decision is bonkers :)

**Comment by ztellman** [comment]
I believe this should address your issue.  If you'd like to add some tests, I'd welcome a PR.
